

-- DROP SEQUENCE "T_SYS_DICTIONARYLIST_SEQ";
CREATE SEQUENCE "T_SYS_DICTIONARYLIST_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_DICTIONARY_SEQ";
CREATE SEQUENCE "T_SYS_DICTIONARY_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;





-- DROP SEQUENCE "T_SYS_LOG1_SEQ";
CREATE SEQUENCE "T_SYS_LOG1_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_LOG_SEQ";
CREATE SEQUENCE "T_SYS_LOG_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_MENU_SEQ";
CREATE SEQUENCE "T_SYS_MENU_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_ROLE_SEQ";
CREATE SEQUENCE "T_SYS_ROLE_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_TABLECOLUMN1_SEQ";
CREATE SEQUENCE "T_SYS_TABLECOLUMN1_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_TABLEINFO1_SEQ";
CREATE SEQUENCE "T_SYS_TABLEINFO1_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_TABLEINFO_SEQ";
CREATE SEQUENCE "T_SYS_TABLEINFO_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_USER_SEQ";
CREATE SEQUENCE "T_SYS_USER_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_ROLEAUTH_SEQ";
CREATE SEQUENCE "T_SYS_ROLEAUTH_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;



-- DROP SEQUENCE "T_SYS_TABLECOLUMN_SEQ";
CREATE SEQUENCE "T_SYS_TABLECOLUMN_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- DROP SEQUENCE "T_SYS_ROLEFIELDS_SEQ";
CREATE SEQUENCE "T_SYS_ROLEFIELDS_SEQ" 
MINVALUE 10000 
MAXVALUE 99999999999999999999 
INCREMENT BY 1 
NOCACHE;

-- ----------------------------
-- 触发器定义（实现自增逻辑）
-- ----------------------------
CREATE OR REPLACE TRIGGER "T_SYS_LOG_TRIGGER" 
BEFORE INSERT ON "SYS_LOG" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.ID IS NULL) 
BEGIN
  SELECT T_SYS_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "T_SYS_USER_TRIGGER" 
BEFORE INSERT ON "SYS_USER" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.USER_ID IS NULL) 
BEGIN
  SELECT T_SYS_USER_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "T_SYS_ROLE_TRIGGER" 
BEFORE INSERT ON "SYS_ROLE" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.ROLE_ID IS NULL) 
BEGIN
  SELECT T_SYS_ROLE_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER "T_SYS_MENU_TRIGGER" 
BEFORE INSERT ON "SYS_MENU" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.MENU_ID IS NULL) 
BEGIN
  SELECT T_SYS_MENU_SEQ.NEXTVAL INTO :NEW.MENU_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "T_SYS_DICTIONARY_TRIGGER" 
BEFORE INSERT ON "SYS_DICTIONARY" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.DIC_ID IS NULL) 
BEGIN
  SELECT T_SYS_DICTIONARY_SEQ.NEXTVAL INTO :NEW.DIC_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "T_SYS_DICTIONARYLIST_TRIGGER" 
BEFORE INSERT ON "SYS_DICTIONARYLIST" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.DICLIST_ID IS NULL) 
BEGIN
  SELECT T_SYS_DICTIONARYLIST_SEQ.NEXTVAL INTO :NEW.DICLIST_ID FROM DUAL;
END;
/



CREATE OR REPLACE TRIGGER "T_SYS_ROLEAUTH_TRIGGER" 
BEFORE INSERT ON "SYS_ROLEAUTH" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.AUTH_ID IS NULL) 
BEGIN
  SELECT T_SYS_ROLEAUTH_SEQ.NEXTVAL INTO :NEW.AUTH_ID FROM DUAL;
END;
/



CREATE OR REPLACE TRIGGER "T_SYS_TABLEINFO_TRIGGER" 
BEFORE INSERT ON "SYS_TABLEINFO" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.TABLE_ID IS NULL) 
BEGIN
  SELECT T_SYS_TABLEINFO_SEQ.NEXTVAL INTO :NEW.TABLE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "T_SYS_TABLECOLUMN_TRIGGER" 
BEFORE INSERT ON "SYS_TABLECOLUMN" 
REFERENCING OLD AS "OLD" NEW AS "NEW" 
FOR EACH ROW 
WHEN (new.COLUMNID IS NULL) 
BEGIN
  SELECT T_SYS_TABLECOLUMN_SEQ.NEXTVAL INTO :NEW.COLUMNID FROM DUAL;
END;
/

